# image: balenalib/raspberrypi3-debian-python

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  
# Global caching directive
cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - .cache/pip

#before_script:
#  - apt-get update -qq && apt-get install -y -qq python3 python3-dev python3-pip
#  - apt-get install pyqt5-dev qt5-default pyqt5-dev-tools
#  - python3 -V
#  - python3 -m pip install --upgrade pip
#  - python3 -m pip --version
  
    
# Deployment section
pages:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk update && apk add python3 python3-dev py3-qt5 build-base
    - python3 -m pip install --upgrade pip
  script:
    - python3 -m pip install sphinx recommonmark sphinx-rtd-theme
    - python3 -m pip install -r requirements.txt
  after_script:
    - sphinx-build --color -b html docs/source public
    - sphinx-build --color -b coverage docs/source coverage
  artifacts:
    paths:
      - public
  only:
    - master
