# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

index_file = open("index.rst", "r")
file_content = index_file.readlines()

index_file.close()
modules_index = 0
modules_last_index = 0

# Find the insertion location for th module location in the index.rst
for index, line in enumerate(file_content):
    if line.find(":caption: Contents:") is not -1:
        modules_index = index + 2  # Do not touch the newline between the data and comment
    elif line.find(".. PYTHON_MODULES_LIST_END") is not -1:
        modules_last_index = index - 1

# Add all the necessary python file containing folder to search path
sys.path.insert(0, os.path.abspath('../../'))
sys.path.append(os.path.abspath('../../Core/'))
for directory in os.listdir(os.path.abspath('../../Core/')):
    if directory.find("__") is -1 and directory.find(".py") is -1:
        sys.path.append(os.path.abspath("../../Core/" + directory))

        # Generate RST files for each python file containing folder
        if not os.path.exists("rst/" + directory):
            os.makedirs("rst/" + directory)
        if not os.listdir("rst/" + directory):
            os.system("sphinx-apidoc -o rst/" + directory + " ../../Core/" + directory)

        # Add the rst file locations in the index.rst
        if ("   " + file_content[modules_index].split("/")[0]) != ("   " + directory):
            if modules_index <= modules_last_index:
                file_content.pop(modules_index)
            file_content.insert(modules_index, "   rst/" + directory + "/modules\n")
            modules_index += 1  # Go to the next line

# Write the modules in the index.rst file
index_file = open("index.rst", "w")
index_file.writelines(file_content)
index_file.close()


# -- Project information -----------------------------------------------------

project = 'Radio Telescope Antenna Controller'
copyright = '2019, Dimitrios Stoupis'
author = 'Dimitrios Stoupis'

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = '0.5'


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []
autodoc_mock_imports = ['RPi.GPIO']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'RadioTelescopeAntennaControllerdoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'RadioTelescopeAntennaController.tex', 'Radio Telescope Antenna Controller Documentation',
     'Dimitrios Stoupis', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'radiotelescopeantennacontroller', 'Radio Telescope Antenna Controller Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'RadioTelescopeAntennaController', 'Radio Telescope Antenna Controller Documentation',
     author, 'RadioTelescopeAntennaController', 'One line description of project.',
     'Miscellaneous'),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']


# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'https://docs.python.org/': None}

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True
